### ISSUE TITLE
Add Leanne's photo

### ISSUE THREAD

**Issue by smythp** [DHRI-Curriculum/Dhrift-Homepage#22]

**Comment by smythp** [comment]
Hi @leanne-fan , can you send me your photo sometime this week?

**Comment by leanne-fan** [comment]
Thank you!! let me know if you prefer a "professional" headshot - I would need to take one but if something more informal works...I like this picture of me!

![LFan_Photo](https://github.com/DHRI-Curriculum/Dhrift-Homepage/assets/72720121/e4bbc420-b77b-441e-b6f4-e951faefb1e0)

**Comment by smythp** [comment]
Should be fine! :) Thanks, Leanne.
