### ISSUE TITLE
Remove me from collaborators

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/Dhrift-Homepage#25]
Hi @smythp - I am receiving notifications for every issue and PR related to the `Dhrift-Homepage` repo. Would you be able to remove me as a collaborator on the repository? Thanks!

**Comment by smythp** [comment]
Hi @kallewesterling , hope you're having a good spring, and sorry you're getting spammed.

You're not explicitly a collaborator on this repo, but you are watching it. My recommendation is to hit the  "unwatch" button on the top right on most pages of the repo (with the icon of the eye) and select either not to watch the repo at all, or only if you are mentioned, depending on preference.

If you're following the organization (I'm guessing you are), then I think you'll be subscribed to watch new repos when they are created. I'd also recommend unfollowing the organization, or alternatively making sure to unwatch new repos if you're prefer not to unfollow. You can unfollow from the main organization page (DHRI-curriculum).

I think that will work, but if you take these steps and you're still getting email, I'll look into removing you from the organization entirely.

**Comment by kallewesterling** [comment]
Hello + happy Spring!

I am still an owner of [this team](https://github.com/orgs/DHRI-Curriculum/people) and I think it might be good to "downgrade" me to an outside collaborator, at least: 

<img width="1601" alt="image" src="https://user-images.githubusercontent.com/7298727/228285418-07944592-7bda-414d-af68-84d422e4ee2c.png">

When I try to do it myself, I get this error message:

<img width="860" alt="image" src="https://user-images.githubusercontent.com/7298727/228286193-813bf7c8-81ce-43d7-a59c-454234b26735.png">

**Comment by smythp** [comment]
OK, looks like @zipper3030 , @dhinstitutes , and @szweibel  are owners. I am not.

Steve, can you remove Kalle as an owner? Maybe also make me an admin as well. Zach, you could also do this. You should be able to do it from the People tab on the organization.

Kind of annoying you can't remove yourself from an organization.

**Comment by szweibel** [comment]
It is done.
