### ISSUE TITLE
Correct Alt tags and icon names in landing page

### ISSUE THREAD

**Issue by lmrhody** [DHRI-Curriculum/Dhrift-Homepage#37]
As I'm working through the call to action text blocks, I'm noticing that the alt tagging isn't accurate. We need to go through these and clean them up so that they reflect what's actually there...

**Comment by szweibel** [comment]
Fixed?

**Comment by lmrhody** [comment]
Yes... what is the "icon": field for, though?

**Comment by szweibel** [comment]
We used to have icons there. I’ll remove it.
