### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by smythp** [DHRI-Curriculum/Dhrift-Homepage#9]
@leanne-fan, can you share a folder of images with me? Stuff from past events, etc. 

cc @szweibel

**Comment by leanne-fan** [comment]
Sorry for the delay, Patrick!
Is this what you were looking for? https://drive.google.com/drive/folders/11GpsLCMP5WYnOR89Pr8sdRLDXYQEa5Zm?usp=sharing

**Comment by smythp** [comment]
Hi @leanne-fan , I was thinking something along the lines of people in a workshop context, i.e. people at one of the Institutes or similar. I may have access to some old photos from my GCDI days, but something newer if photos have more recently been taken would be a help. @szweibel , have anything from your participation, or seen anything alone these lines?

**Comment by leanne-fan** [comment]
Google Drive of pre-covid DHRI Workshops: https://drive.google.com/drive/folders/1D4-yzfQChAoI0hA-kM-hLrSO_SDGq74R?usp=share_link

<img width="576" alt="DHRI_SpringOfficeHours" src="https://user-images.githubusercontent.com/72720121/224118386-eba20776-66a0-4195-8c87-868b36e57779.png">
<img width="1190" alt="DHRI august reconvening" src="https://user-images.githubusercontent.com/72720121/224118390-cde0647e-f53c-42fc-9e86-c39d10083671.png">

**Comment by smythp** [comment]
Thank you! :)

**Comment by smythp** [comment]
Perfect, thanks! :smile:
